version: '3.4'

services:
  servicesstore.api.authors:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6104:80"
  servicesstore.api.book:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"
